"""Add interview_level_outcomes table

Revision ID: 10e3e50acc80
Revises: ac4c2ebfd4af
Create Date: 2026-03-06 01:30:44.098108
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10e3e50acc80'
down_revision = 'ac4c2ebfd4af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create interview_level_outcomes table
    op.create_table(
        'interview_level_outcomes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(length=100), nullable=False),
        sa.Column('company_tier', sa.String(length=50), nullable=False),
        sa.Column('estimated_level', sa.String(length=100), nullable=False),
        sa.Column('estimated_level_display', sa.String(length=200), nullable=False),
        sa.Column('readiness_percent', sa.Integer(), nullable=False),
        sa.Column('confidence', sa.String(length=50), nullable=False),
        sa.Column('next_level', sa.String(length=100), nullable=True),
        sa.Column('strengths', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('gaps', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('next_actions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('rubric_scores_used', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('interview_level_outcomes_pkey')),
        sa.UniqueConstraint('session_id', name=op.f('interview_level_outcomes_session_id_key'))
    )
    op.create_index(op.f('ix_interview_level_outcomes_role'), 'interview_level_outcomes', ['role'], unique=False)
    op.create_index(op.f('ix_interview_level_outcomes_session_id'), 'interview_level_outcomes', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_level_outcomes_session_id'), table_name='interview_level_outcomes')
    op.drop_index(op.f('ix_interview_level_outcomes_role'), table_name='interview_level_outcomes')
    op.drop_table('interview_level_outcomes')
    
    # Restore user_usage table
    op.create_table('user_usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chat_messages_today', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('chat_reset_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('tts_characters_month', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('usage_month', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('total_chat_messages', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_tts_characters', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_interview_sessions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_usage_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_usage_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user_usage_user_id_key'))
    )
    op.create_index(op.f('ix_user_usage_user_id'), 'user_usage', ['user_id'], unique=True)
    
    # Restore admin_accounts table
    op.create_table('admin_accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_accounts_pkey')),
    sa.UniqueConstraint('username', name=op.f('admin_accounts_username_key'))
    )
    op.create_index(op.f('ix_admin_accounts_username'), 'admin_accounts', ['username'], unique=True)
    # ### end Alembic commands ###
