"""initial schema

Revision ID: 135bba521b46
Revises: 
Create Date: 2026-01-11 13:57:15.358819
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135bba521b46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    # ### end Alembic commands ###
