"""initial schema

Revision ID: 18cf6cdcef47
Revises: 135bba521b46
Create Date: 2026-01-11 14:07:46.886651
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18cf6cdcef47'
down_revision = '135bba521b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
