"""add_chat_threads_table

Revision ID: 5d8533fcfb18
Revises: a8c3e5f7b9d1
Create Date: 2026-02-02 23:54:58.872756
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d8533fcfb18'
down_revision = 'a8c3e5f7b9d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_threads_user_id'), 'chat_threads', ['user_id'], unique=False)
    op.execute(sa.text("DROP INDEX IF EXISTS ix_audit_logs_action"))
    op.alter_column('interview_sessions', 'difficulty_current',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('interview_sessions', 'questions_asked_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('interview_sessions', 'followups_used',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('interview_sessions', 'max_questions',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('interview_sessions', 'max_followups_per_question',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('interview_sessions', 'behavioral_questions_target',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('interview_sessions', 'skill_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_constraint(op.f('question_embeddings_question_id_key'), 'question_embeddings', type_='unique')
    op.alter_column('questions', 'followups',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('questions', 'question_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('questions', 'meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('response_examples', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_response_examples_category'), table_name='response_examples')
    op.drop_index(op.f('ix_response_examples_is_active'), table_name='response_examples')
    op.drop_index(op.f('ix_response_examples_quality_label'), table_name='response_examples')
    op.drop_index(op.f('ix_session_embeddings_feedback_rating'), table_name='session_embeddings')
    op.drop_constraint(op.f('session_embeddings_session_id_key'), 'session_embeddings', type_='unique')
    op.drop_index(op.f('ix_session_feedback_rating'), table_name='session_feedback')
    op.drop_constraint(op.f('session_feedback_session_id_key'), 'session_feedback', type_='unique')
    op.alter_column('users', 'role_pref',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'profile',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'profile',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               existing_nullable=False)
    op.alter_column('users', 'role_pref',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'SWE Intern'::character varying"),
               existing_nullable=False)
    op.create_unique_constraint(op.f('session_feedback_session_id_key'), 'session_feedback', ['session_id'])
    op.create_index(op.f('ix_session_feedback_rating'), 'session_feedback', ['rating'], unique=False)
    op.create_unique_constraint(op.f('session_embeddings_session_id_key'), 'session_embeddings', ['session_id'])
    op.create_index(op.f('ix_session_embeddings_feedback_rating'), 'session_embeddings', ['feedback_rating'], unique=False)
    op.create_index(op.f('ix_response_examples_quality_label'), 'response_examples', ['quality_label'], unique=False)
    op.create_index(op.f('ix_response_examples_is_active'), 'response_examples', ['is_active'], unique=False)
    op.create_index(op.f('ix_response_examples_category'), 'response_examples', ['category'], unique=False)
    op.alter_column('response_examples', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('questions', 'meta',
               existing_type=sa.JSON(),
               server_default=sa.text("'{}'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('questions', 'question_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'coding'::character varying"),
               existing_nullable=False)
    op.alter_column('questions', 'followups',
               existing_type=sa.JSON(),
               server_default=sa.text("'[]'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_unique_constraint(op.f('question_embeddings_question_id_key'), 'question_embeddings', ['question_id'])
    op.alter_column('interview_sessions', 'skill_state',
               existing_type=sa.JSON(),
               server_default=sa.text("'{}'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('interview_sessions', 'behavioral_questions_target',
               existing_type=sa.INTEGER(),
               server_default=sa.text('2'),
               existing_nullable=False)
    op.alter_column('interview_sessions', 'max_followups_per_question',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    op.alter_column('interview_sessions', 'max_questions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    op.alter_column('interview_sessions', 'followups_used',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('interview_sessions', 'questions_asked_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('interview_sessions', 'difficulty_current',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'easy'::character varying"),
               existing_nullable=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.drop_index(op.f('ix_chat_threads_user_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    # ### end Alembic commands ###
