"""add_company_tier_to_interview_sessions

Revision ID: f2707d628860
Revises: 10e3e50acc80
Create Date: 2026-03-06 13:45:56.143635
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2707d628860'
down_revision = '10e3e50acc80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('company_tier', sa.String(length=50), server_default='startup', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'company_tier')
    # ### end Alembic commands ###
